version: '3.1'
services:
  server:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: task2
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5555:5432"
    volumes:
      - ./var_lib_postgresql:/var/lib/postgresql/data

  client:
    build:
      context: .
    tty: true
    depends_on:
      - server
